# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        candidat_photo:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        candidat_cv:
            uri_prefix: /uploads/cvs
            upload_destination: '%kernel.project_dir%/public/uploads/cvs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        candidat_passeport:
            uri_prefix: /uploads/passeports
            upload_destination: '%kernel.project_dir%/public/uploads/passeports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer